# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 */12 * * *"
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21', '1.22' ]
        os: [ 'ubuntu-latest', 'macOS-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Run gofmt
      run: test -z "$(go fmt ./...)"
      shell: bash

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
